version: "3.9"
services:
  chatgpt-next-web:
    profiles: ["no-proxy"]
    container_name: chatgpt-next-web
    image: gosuto/chatgpt-next-web-langchain
    volumes:
      - next_chat_upload:/app/uploads
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - CODE=$CODE
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - OPENAI_SB=$OPENAI_SB

  chatgpt-next-web-proxy:
    profiles: ["proxy"]
    container_name: chatgpt-next-web-proxy
    image: gosuto/chatgpt-next-web-langchain
    volumes:
      - next_chat_upload:/app/uploads
    ports:
      - 3000:3000
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - GOOGLE_API_KEY=$GOOGLE_API_KEY
      - CODE=$CODE
      - PROXY_URL=$PROXY_URL
      - BASE_URL=$BASE_URL
      - OPENAI_ORG_ID=$OPENAI_ORG_ID
      - HIDE_USER_API_KEY=$HIDE_USER_API_KEY
      - OPENAI_SB=$OPENAI_SB

volumes:
  next_chat_upload:
